# Generated by Django 5.2.7 on 2025-10-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=50)),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
                ('post_url', models.URLField()),
                ('has_tagged_digitalocean', models.BooleanField(default=False)),
                ('has_starred_repo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
